# exec = export SLURP_ARGS='-d -c F5D9FFBB -b 56416144 -s 00000000'

general {
    col.active_border = rgba(E9DFEE39)
    col.inactive_border = rgba(968D9E30)
}

misc {
    background_color = rgba(16121BFF)
}

plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(16121BFF)
        col.text = rgba(E9DFEEFF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
        hyprbars-button = rgb(E9DFEE), 13, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(E9DFEE), 13, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(E9DFEE), 13, 󰖰, hyprctl dispatch movetoworkspacesilent special
    }
}

windowrulev2 = bordercolor rgba(D6BAFFAA) rgba(D6BAFF77),pinned:1